name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Copy settings.xml to .m2 folder
        run: |
            cp settings.xml ~/.m2/settings.xml

      - name: Publish to Sonatype Packages
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_USERNAME }}
        run: mvn clean deploy --settings ~/.m2/settings.xml
