name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Create settings.xml
        run: |
            echo "<settings>" > settings.xml
            echo "  <servers>" >> settings.xml
            echo "    <server>" >> settings.xml
            echo "      <id>central</id>" >> settings.xml
            echo "      <username>${{ secrets.MAVEN_USERNAME }}</username>" >> settings.xml
            echo "      <password>${{ secrets.MAVEN_USERNAME }}</password>" >> settings.xml
            echo "    </server>" >> settings.xml
            echo "  </servers>" >> settings.xml
            echo "</settings>" >> settings.xml

      - name: Publish to Sonatype Packages
        run: mvn clean deploy
